version: '3.8'

services:
  # Config Servers
  mongodb-config-1:
    image: mongo:6.0
    container_name: config1
    hostname: config1
    command: mongod --configsvr --replSet configrs --bind_ip_all --port 27017
    volumes:
      - mongodb_config_data_1:/data/db
      - mongodb_config_data_1:/data/configdb
    networks:
      - mongodb-cluster

  mongodb-config-2:
    image: mongo:6.0
    container_name: config2
    hostname: config2
    command: mongod --configsvr --replSet configrs --bind_ip_all --port 27017
    volumes:
      - mongodb_config_data_2:/data/db
      - mongodb_config_data_2:/data/configdb
    networks:
      - mongodb-cluster

  mongodb-config-3:
    image: mongo:6.0
    container_name: config3
    hostname: config3
    command: mongod --configsvr --replSet configrs --bind_ip_all --port 27017
    volumes:
      - mongodb_config_data_3:/data/db
      - mongodb_config_data_3:/data/configdb
    networks:
      - mongodb-cluster

  # Shard 1
  mongodb-shard1:
    image: mongo:6.0
    container_name: shard1
    hostname: shard1
    command: mongod --shardsvr --bind_ip_all --port 27017
    volumes:
      - mongodb_shard1_data:/data/db
    networks:
      - mongodb-cluster

  # Shard 2
  mongodb-shard2:
    image: mongo:6.0
    container_name: shard2
    hostname: shard2
    command: mongod --shardsvr --bind_ip_all --port 27017
    volumes:
      - mongodb_shard2_data:/data/db
    networks:
      - mongodb-cluster

  # Shard 3
  mongodb-shard3:
    image: mongo:6.0
    container_name: shard3
    hostname: shard3
    command: mongod --shardsvr --bind_ip_all --port 27017
    volumes:
      - mongodb_shard3_data:/data/db
    networks:
      - mongodb-cluster

  # Mongos Router
  mongos:
    image: mongo:6.0
    container_name: mongos
    hostname: mongos
    command: mongos --configdb configrs/config1:27017,config2:27017,config3:27017 --bind_ip_all --port 27017
    ports:
      - "27018:27017"
    depends_on:
      - mongodb-config-1
      - mongodb-config-2
      - mongodb-config-3
      - mongodb-shard1
      - mongodb-shard2
      - mongodb-shard3
    networks:
      - mongodb-cluster

volumes:
  mongodb_config_data_1:
  mongodb_config_data_2:
  mongodb_config_data_3:
  mongodb_shard1_data:
  mongodb_shard2_data:
  mongodb_shard3_data:

networks:
  mongodb-cluster:
    driver: bridge