version: '3.9'

services:
  # Config servers
  config1:
    image: mongo:6.0
    container_name: config1
    command: ["mongod", "--configsvr", "--replSet", "configrs", "--port", "27017"]
    networks:
      - mongodb-cluster
    ports:
      - "27019:27017"
    volumes:
      - config1_data:/data/db

  config2:
    image: mongo:6.0
    container_name: config2
    command: ["mongod", "--configsvr", "--replSet", "configrs", "--port", "27017"]
    networks:
      - mongodb-cluster
    ports:
      - "27020:27017"
    volumes:
      - config2_data:/data/db

  config3:
    image: mongo:6.0
    container_name: config3
    command: ["mongod", "--configsvr", "--replSet", "configrs", "--port", "27017"]
    networks:
      - mongodb-cluster
    ports:
      - "27021:27017"
    volumes:
      - config3_data:/data/db

  # Shards
  shard1:
    image: mongo:6.0
    container_name: shard1
    command: ["mongod", "--shardsvr", "--replSet", "shard1rs", "--port", "27017"]
    networks:
      - mongodb-cluster
    ports:
      - "27117:27017"
    volumes:
      - shard1_data:/data/db

  shard2:
    image: mongo:6.0
    container_name: shard2
    command: ["mongod", "--shardsvr", "--replSet", "shard2rs", "--port", "27017"]
    networks:
      - mongodb-cluster
    ports:
      - "27217:27017"
    volumes:
      - shard2_data:/data/db

  shard3:
    image: mongo:6.0
    container_name: shard3
    command: ["mongod", "--shardsvr", "--replSet", "shard3rs", "--port", "27017"]
    networks:
      - mongodb-cluster
    ports:
      - "27317:27017"
    volumes:
      - shard3_data:/data/db

  # Mongos router
  mongos:
    image: mongo:6.0
    container_name: mongos
    command: ["mongos", "--configdb", "configrs/config1:27017,config2:27017,config3:27017", "--bind_ip_all"]
    networks:
      - mongodb-cluster
    ports:
      - "27017:27017"

volumes:
  config1_data:
  config2_data:
  config3_data:
  shard1_data:
  shard2_data:
  shard3_data:

networks:
  mongodb-cluster:
    driver: bridge
